-- 评估按单注 2 元固定奖表计奖金，不取当期浮动奖池。
ALTER TABLE prediction_results ADD COLUMN IF NOT EXISTS stake_yuan DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_results ADD COLUMN IF NOT EXISTS prize_yuan DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_results ADD COLUMN IF NOT EXISTS profit_yuan DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_results ADD COLUMN IF NOT EXISTS prize_floating BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS total_wins INT NOT NULL DEFAULT 0;
ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS total_stake DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS total_prize DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS total_profit DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS last_30_wins INT NOT NULL DEFAULT 0;
ALTER TABLE prediction_accuracy ADD COLUMN IF NOT EXISTS last_30_profit DOUBLE PRECISION NOT NULL DEFAULT 0;
